## 项目信息
#project:
#  name: Codegen
#  version: v1.0.0
#  env: development
#
## WEB服务器端口配置
#server:
#  port: 8080
#
## Spring配置
#spring:
#  # 数据源配置
#  datasource:
#    url: jdbc:mysql://rm-bp15iscz0t1m98qk8o.mysql.rds.aliyuncs.com:3306/db_demo?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=true
#    username: cg_demo
#    password: cg_demo
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    type: com.alibaba.druid.pool.DruidDataSource
#  # JSON返回配置
#  jackson:
#    # 默认时区
#    time-zone: GMT+8
#    ## 默认日期格式化
#    date-format: yyyy-MM-dd HH:mm:ss
#  # 静态资源配置
#  resources:
#    # Thymeleaf
#    # static-locations: classpath:/META-INF/resources/, classpath:/META-INF/resources/webjars/, classpath:/static/
#    # JSP
#    static-locations: classpath:/META-INF/resources/, classpath:/META-INF/resources/webjars/
#  # Thymeleaf配置
#  #thymeleaf:
#    #cache: false
#  # JSP配置
#  mvc:
#    view:
#      suffix: .jsp
#      prefix: /WEB-INF/pages/
#
## MyBatis配置
#mybatis:
#  #对应mappers映射xml文件的所在路径
#  mapper-locations: classpath:/mappers/*.xml
#  configuration:
#    # 使用resultType时自动将下划线转为驼峰命名
#    map-underscore-to-camel-case: true
#
## logback信息配置
#logback:
#  level: INFO
#  appender: ${project.env}
#
## dao层的日志设置为debug，方便查看sql
#logging:
#  level:
#    com.codegen.dao: debug
#
## Swagger配置
#swagger:
#  host:
#  title: Codegen接口文档
#  description:  Codegen接口文档
#  # 是否禁用swagger
#  disabled: true
#  # 禁用swagger时的重定向地址
#  redirect-uri: /